// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class merged_from_student_api : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merged_from_student_api));
        
        string IMigrationMetadata.Id
        {
            get { return "201902081542561_merged_from_student_api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
